Fix Rakefile problem "rake/rdoctask is obsolete"
Full error:

rake aborted!
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task'
(available in RDoc 2.4.2+) instead.
/home/void/Coding/padrino-responders/Rakefile:53:in `<top (required)>''`